# Generated by Django 3.1.7 on 2021-03-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idname', models.CharField(db_index=True, max_length=64, unique=True)),
                ('finished', models.IntegerField(db_index=True)),
                ('boxes', models.TextField()),
                ('prop_occluded', models.IntegerField()),
                ('prop_art', models.IntegerField()),
                ('prop_st', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
